// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.5
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CentralSourceClient is the client API for CentralSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CentralSourceClient interface {
	Push(ctx context.Context, in *PushQ, opts ...grpc.CallOption) (*PushS, error)
	AddToken(ctx context.Context, in *AddTokenQ, opts ...grpc.CallOption) (*AddTokenS, error)
	Ping(ctx context.Context, in *PingQS, opts ...grpc.CallOption) (*PingQS, error)
}

type centralSourceClient struct {
	cc grpc.ClientConnInterface
}

func NewCentralSourceClient(cc grpc.ClientConnInterface) CentralSourceClient {
	return &centralSourceClient{cc}
}

func (c *centralSourceClient) Push(ctx context.Context, in *PushQ, opts ...grpc.CallOption) (*PushS, error) {
	out := new(PushS)
	err := c.cc.Invoke(ctx, "/CentralSource/push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralSourceClient) AddToken(ctx context.Context, in *AddTokenQ, opts ...grpc.CallOption) (*AddTokenS, error) {
	out := new(AddTokenS)
	err := c.cc.Invoke(ctx, "/CentralSource/addToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralSourceClient) Ping(ctx context.Context, in *PingQS, opts ...grpc.CallOption) (*PingQS, error) {
	out := new(PingQS)
	err := c.cc.Invoke(ctx, "/CentralSource/ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CentralSourceServer is the server API for CentralSource service.
// All implementations must embed UnimplementedCentralSourceServer
// for forward compatibility
type CentralSourceServer interface {
	Push(context.Context, *PushQ) (*PushS, error)
	AddToken(context.Context, *AddTokenQ) (*AddTokenS, error)
	Ping(context.Context, *PingQS) (*PingQS, error)
	mustEmbedUnimplementedCentralSourceServer()
}

// UnimplementedCentralSourceServer must be embedded to have forward compatible implementations.
type UnimplementedCentralSourceServer struct {
}

func (UnimplementedCentralSourceServer) Push(context.Context, *PushQ) (*PushS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedCentralSourceServer) AddToken(context.Context, *AddTokenQ) (*AddTokenS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToken not implemented")
}
func (UnimplementedCentralSourceServer) Ping(context.Context, *PingQS) (*PingQS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCentralSourceServer) mustEmbedUnimplementedCentralSourceServer() {}

// UnsafeCentralSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CentralSourceServer will
// result in compilation errors.
type UnsafeCentralSourceServer interface {
	mustEmbedUnimplementedCentralSourceServer()
}

func RegisterCentralSourceServer(s grpc.ServiceRegistrar, srv CentralSourceServer) {
	s.RegisterService(&CentralSource_ServiceDesc, srv)
}

func _CentralSource_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushQ)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralSourceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CentralSource/push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralSourceServer).Push(ctx, req.(*PushQ))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralSource_AddToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTokenQ)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralSourceServer).AddToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CentralSource/addToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralSourceServer).AddToken(ctx, req.(*AddTokenQ))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralSource_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingQS)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralSourceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CentralSource/ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralSourceServer).Ping(ctx, req.(*PingQS))
	}
	return interceptor(ctx, in, info, handler)
}

// CentralSource_ServiceDesc is the grpc.ServiceDesc for CentralSource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CentralSource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CentralSource",
	HandlerType: (*CentralSourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "push",
			Handler:    _CentralSource_Push_Handler,
		},
		{
			MethodName: "addToken",
			Handler:    _CentralSource_AddToken_Handler,
		},
		{
			MethodName: "ping",
			Handler:    _CentralSource_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// KiriyamaClient is the client API for Kiriyama service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KiriyamaClient interface {
	GetStatus(ctx context.Context, in *GetStatusQ, opts ...grpc.CallOption) (Kiriyama_GetStatusClient, error)
}

type kiriyamaClient struct {
	cc grpc.ClientConnInterface
}

func NewKiriyamaClient(cc grpc.ClientConnInterface) KiriyamaClient {
	return &kiriyamaClient{cc}
}

func (c *kiriyamaClient) GetStatus(ctx context.Context, in *GetStatusQ, opts ...grpc.CallOption) (Kiriyama_GetStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &Kiriyama_ServiceDesc.Streams[0], "/Kiriyama/getStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &kiriyamaGetStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kiriyama_GetStatusClient interface {
	Recv() (*GetStatusS, error)
	grpc.ClientStream
}

type kiriyamaGetStatusClient struct {
	grpc.ClientStream
}

func (x *kiriyamaGetStatusClient) Recv() (*GetStatusS, error) {
	m := new(GetStatusS)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KiriyamaServer is the server API for Kiriyama service.
// All implementations must embed UnimplementedKiriyamaServer
// for forward compatibility
type KiriyamaServer interface {
	GetStatus(*GetStatusQ, Kiriyama_GetStatusServer) error
	mustEmbedUnimplementedKiriyamaServer()
}

// UnimplementedKiriyamaServer must be embedded to have forward compatible implementations.
type UnimplementedKiriyamaServer struct {
}

func (UnimplementedKiriyamaServer) GetStatus(*GetStatusQ, Kiriyama_GetStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedKiriyamaServer) mustEmbedUnimplementedKiriyamaServer() {}

// UnsafeKiriyamaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KiriyamaServer will
// result in compilation errors.
type UnsafeKiriyamaServer interface {
	mustEmbedUnimplementedKiriyamaServer()
}

func RegisterKiriyamaServer(s grpc.ServiceRegistrar, srv KiriyamaServer) {
	s.RegisterService(&Kiriyama_ServiceDesc, srv)
}

func _Kiriyama_GetStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetStatusQ)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KiriyamaServer).GetStatus(m, &kiriyamaGetStatusServer{stream})
}

type Kiriyama_GetStatusServer interface {
	Send(*GetStatusS) error
	grpc.ServerStream
}

type kiriyamaGetStatusServer struct {
	grpc.ServerStream
}

func (x *kiriyamaGetStatusServer) Send(m *GetStatusS) error {
	return x.ServerStream.SendMsg(m)
}

// Kiriyama_ServiceDesc is the grpc.ServiceDesc for Kiriyama service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kiriyama_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Kiriyama",
	HandlerType: (*KiriyamaServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getStatus",
			Handler:       _Kiriyama_GetStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
