#!/bin/bash

set -eu

name="$1"
private_key="$2"
address="$3"
post_up="$4"
post_down="$5"
after="$6"
listen_port="$7"
wg="$8"
wg_quick="$9"

umask 077
mkdir -p /etc/wireguard
cat > "/etc/wireguard/$name.conf" << EOF
# Generated by Qrystal-mio for network $name. DO NOT EDIT.
# This file will be overwritten during sync.
[Interface]
PrivateKey=$private_key
Address=$address
ListenPort=$listen_port

PostUp=$post_up
PostDown=$post_down

# After:
$after
EOF

ifaces=($($wg show interfaces))

log=$(mktemp)

if [[ " ${ifaces[*]} " =~ " $name " ]]; then
	# TODO: syncconf if ips don't change
	$wg_quick down "$name" 2> $log || 1>&2 cat $log
fi

#$wg_quick up "$name" 2> $log || 1>&2 cat $log
$wg_quick up "$name"
rm $log
