#!/bin/sh

set -eux

name="$1"
private_key="$2"
address="$3"
post_up="$4"
post_down="$5"
after="$6"

echo after "$after"

umask 077
cat > "/etc/wireguard/$name.conf" << EOF
# Generated by Qrystal-mio for network $name. DO NOT EDIT.
# This file will be overwritten during sync.
[Interface]
PrivateKey=$private_key
Address=$address

PostUp=$post_up
PostDown=$post_down

# After:
$after
EOF

wg-quick up "$name"
