#!/bin/sh

set -eu

name="$1"
private_key="$2"
address="$3"
post_up="$4"
post_down="$5"
after="$6"
op="$7"

umask 077
cat > "/etc/wireguard/$name.conf" << EOF
# Generated by Qrystal-mio for network $name. DO NOT EDIT.
# This file will be overwritten during sync.
[Interface]
PrivateKey=$private_key
Address=$address

PostUp=$post_up
PostDown=$post_down

# After:
$after
EOF

if [[ "$op" == "add" ]]; then
	wg-quick up "$name"
else
	wg syncconf "$name" <(wg-quick strip "$name")
fi
