#!/bin/sh

set -eu

name="$1"
private_key="$2"
address="$3"
post_up="$4"
post_down="$5"
after="$6"

umask 077
cat > "/etc/wireguard/$name.conf" << EOF
# Generated by Qrystal-mio for network $name. DO NOT EDIT.
# This file will be overwritten during sync.
[Interface]
PrivateKey=$private_key
Address=$address

PostUp=$post_up
PostDown=$post_down

# After:
$after
EOF

log=$(mktemp)
wg-quick up "$name" 2> $log || 1>&2 cat $log
rm $log
