set -eux

name="$1"
private_key="$2"
address="$3"

umask 077
cat > "/etc/wireguard/$name.conf" << EOF
# Generated by Qanms-mio for network $name
[Interface]
PrivateKey=$private_key
Address=$address
EOF
wg-quick up "$name"
